#!/bin/sh

sudo rm -rf /usr/lib/linuxmint/mintsystem
sudo cp -R etc /
sudo cp -R lib /
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas

sudo /usr/lib/linuxmint/mintsystem/mint-adjust.py
