#! /bin/sh

### BEGIN INIT INFO
# Provides:          mintsystem
# Required-Start:    $local_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0
### END INIT INFO

/usr/lib/linuxmint/mintSystem/mint-adjust.py

