#! /bin/sh

### BEGIN INIT INFO
# Provides:          mintsystem
# Required-Start:    $local_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     S
# Default-Stop:  
### END INIT INFO

# Let's source /lib/lsb/init-functions
. /lib/lsb/init-functions

/usr/lib/linuxmint/mintSystem/mint-adjust.py

