#!/bin/sh

set -e

case "$1" in
deconfigure|remove)

    update-alternatives --remove apt /usr/local/bin/apt

    ;;
esac

set +e
rmdir --ignore-fail-on-non-empty /usr/local/bin
set -e

#DEBHELPER#

exit 0
