.TH SEARCH "1"
.SH NAME
search - Linux Mint command line search tool

.SH SYNOPSIS
.B search
[\fIarguments\fB] [\fIoptions\fB]

.SH DESCRIPTION
.SS "arguments:"
.IP
for text
.br
in directory
.SS "options:"
.HP
\fB\-c\fR | \fB\-\-case\-sensitive\fR
.HP
\fB\-s\fR | \fB\-\-show\-filenames\-only\fR

.SH "SEE ALSO"
.BR find (1)
